### ISSUE TITLE
Suggestion: add support for the box trot mod. It doesn't add new blocks but allows you to put barrels on your head 

### ISSUE THREAD

**Issue by Skel200** [xanthian/variantbarrels#10]
https://www.curseforge.com/minecraft/mc-mods/the-box-trot

**Comment by xanthian** [comment]
That's not in the scope of my mod, you should put the suggestion on the-box-trot

For example , they explicitly say the vanilla barrel, if they used `instanceOf BarrelBlock` it may work with mine.
eg.
`if(stack.getItem() == Items.BARREL && getIndex() == 39)`

But they'll need to create models for every barrel I add, so can't see it happening.
