### ISSUE TITLE
[Remove Mod Compat] Blockus

### ISSUE THREAD

**Issue by FibreTTP** [xanthian/variantbarrels#11]
This issue requires resolution from both mods, and so has been posted to both repositories.

[Variant Barrels](https://github.com/xanthian/variantbarrels) ([CurseForge](https://curseforge.com/minecraft/mc-mods/variant-barrels-fabric)) currently detects [Blockus](https://github.com/Brandcraf06/Blockus) ([CurseForge](https://curseforge.com/minecraft/mc-mods/blockus)) and removes conflicting barrels from the game.

However, as of March 20 2022, Blockus barrel recipes have been [removed from the mod](https://github.com/Brandcraf06/Blockus/issues/223), and since Variant Barrels removes its own barrels, both sets are unobtainable (with Blockus variants requiring cheats, as only the recipe has been removed).

The best way for this to be fixed is if Variant Barrels removes compatibility for Blockus, and Blockus removes barrels from the mod entirely (there are... [issues](https://github.com/Brandcraf06/Blockus/issues/197)).

This has been tested in 1.19.2 with Blockus, EMI, Fabric API, and Variant Barrels.

View this issue at: [Blockus](https://github.com/Brandcraf06/Blockus/issues/286)

**Comment by xanthian** [comment]
@FibreTTP 
I thought I had fixed this but seems I never actually released it!
will try sort it today,

**Comment by xanthian** [comment]
fixed with https://github.com/xanthian/variantbarrels/commit/edb90a6db866c11f6320c2d4b5a64267d2f3190d

**Comment by FibreTTP** [comment]
Thanks!
