### ISSUE TITLE
[Mod Compat] Recipe Confidence (Paradise Lost dependency)

### ISSUE THREAD

**Issue by gudenau** [xanthian/variantbarrels#7]
My mod "[Recipe Confidence](https://github.com/gudenau/minecraft-RecipeConfidence)" conflicts with your implementation of recipe sorting. My mod prioritizes the least fuzzy matching recipe, which should be compatible with this mod's recipes, maybe you can use it as a dependency as well as Paradise Lost.

**Comment by xanthian** [comment]
I cannot replicate this locally with Paradise Lost installed.

Not really a fan of adding dependencies for what is just a simple cosmetic mod.
Also adding Recipe Confidence would then make it incompatible with BetterX mods, not something I really want to do.

**Comment by xanthian** [comment]
In fact, I've just noticed they are using 1.2 version of my mod, I changed the @Overwrite to @Inject in v1.3 so if they try that.

**Comment by xanthian** [comment]
1.3 fixes this.

**Comment by gudenau** [comment]
The Inject at head and cancel breaks my mod, it isn't a fix.

**Comment by xanthian** [comment]
reopened, although unlikely to fix.
not being forced in to using a dependency mod.

as I said, it works fine on my installation with Aether (and your mod) installed.

**Comment by xanthian** [comment]
seems the mixin doesnt work in 1.18.2 anyway, so will look at removing it.

**Comment by xanthian** [comment]
mixin has now been removed in latest version as it does not work in 1.18.2 anyway.
