### ISSUE TITLE
More variant blocks : Bookshelf and Lectern

### ISSUE THREAD

**Issue by Aeredren** [xanthian/variantbarrels#9]
Hi ! As I see you are really into variated woods, there is also bookshelf and lectern which used a standard oak texture (which is very frustrating when building library out of spruce and barrels). So maybee if you have some time left ^^

**Comment by xanthian** [comment]
I started on these on a different mod, but didn't get far as was some complications and mod wasn't very popular.

https://www.curseforge.com/minecraft/mc-mods/variant-sticks-stuff
